name: Frontend CI/CD

on:
  push:
    branches:
      - develop  # Verifica se você tem branch 'develop'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.19.1'  # Versão específica - boa prática!

      - name: Install dependencies
        run: npm ci  # CI é melhor que INSTALL para CI/CD - boa!

      - name: Run Linter
        run: npm run lint  # Verifica se tem ESLint configurado

      - name: Build project
        run: npm run build  # Testa se o build funciona